### PR TITLE
Typescript overhaul

### PR DESCRIPTION
**Pull request by daviseford**
@randombishop please test this one locally very carefully

Make sure to re-run `yarn install` in `/app`

I tried to leave all original functionality identical. Just converted what I could to the latest React hooks/functional components style. Also typed a whole lot of things

### CODE REVIEW

**Comment by randombishop** [comment]
Amazing refactoring. Never used TypeScript before, good occasion for me to learn!
Just did some tests and everything seems to be working as expected except a couple of regressions:
- The DRAW button in the voting page is not working (nothing happens.)
- The Results button when opening a specific lore in the Rankings page is not working neither.

**Comment by daviseford** [comment]
Will fix over the next couple days. Cheers!

**Comment by daviseford** [comment]
Should be good to go now!

**Comment by randombishop** [comment]
Another bug if you click on Results in a runner who still doesn't have votes
Screen Shot 2021-11-26 at 9 49 32 AM
Sorry can't help you debugging, have a lot of work this week...

**Review by randombishop — APPROVED** [review]
LG
Thanks for the hard work!

**Pull request merged**
